development:
  adapter: postgresql
  encoding: unicode
  database: flatmate_dev
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: flatmate_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: flatmate_prod
  username: postgres
  password: postgres
  host: localhost
